version: '3.8'

services:
  db:
    image: postgres:16 # Możesz wybrać konkretną wersję PostgreSQL
    container_name: shelfsense_db
    restart: always
    environment:
      POSTGRES_DB: shelfsense_db # Nazwa bazy danych
      POSTGRES_USER: shelfsense_user # Nazwa użytkownika
      POSTGRES_PASSWORD: your_strong_password # Zmień na silne hasło!
    ports:
      - "5432:5432" # Mapowanie portu hosta na port kontenera
    volumes:
      - postgres_data:/var/lib/postgresql/data # Wolumen do przechowywania danych bazy danych
      - ./db/schema.sql:/docker-entrypoint-initdb.d/init.sql # Kopiowanie schematu do inicjalizacji
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shelfsense_user -d shelfsense_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: # Definicja wolumenu
